# Generated by Django 4.2.1 on 2023-05-11 20:10

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=18, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_employment', models.DateField(verbose_name='Дата приема на работу')),
                ('date_of_dismissal', models.DateField(verbose_name='Дата увольнения')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_delivery', models.DateField(verbose_name='Дата доставки')),
                ('time_of_order', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
                ('address_of_delivery', models.CharField(max_length=128, verbose_name='Адрес доставки')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая стоимость')),
                ('commentary_for_order', models.TextField(verbose_name='Комментарий к заказу')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.customer', verbose_name='Заказчик')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateField(auto_now_add=True, verbose_name='Дата утверждения прайс-листа')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('weight', models.IntegerField(verbose_name='Вес (гр.)')),
                ('image', models.ImageField(upload_to='products_img/')),
            ],
        ),
        migrations.CreateModel(
            name='StateOfOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Статус заказа')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='tags_img/')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Тип оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='TagAndProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.tag', verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='PriceListPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('units', models.CharField(max_length=32, verbose_name='Единица измерения')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.pricelist', verbose_name='Прайс-лист')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_products', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('price_of_position', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость позиции')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.pricelistposition', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAndState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.employee', verbose_name='Работник')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.order', verbose_name='Заказ')),
                ('state_of_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.stateoforder', verbose_name='Статус заказа')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='type_of_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.typeofpayment', verbose_name='Тип оплаты'),
        ),
    ]
