# Generated by Django 4.1.7 on 2023-05-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderandstate',
            options={'verbose_name': 'Заказ и статус', 'verbose_name_plural': 'Заказы и статусы'},
        ),
        migrations.AlterModelOptions(
            name='orderposition',
            options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказов'},
        ),
        migrations.AlterModelOptions(
            name='pricelist',
            options={'verbose_name': 'Прайс-лист', 'verbose_name_plural': 'Прайс-листы'},
        ),
        migrations.AlterModelOptions(
            name='pricelistposition',
            options={'verbose_name': 'Позиция прайс-листа', 'verbose_name_plural': 'Позиции прайс-листов'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='stateoforder',
            options={'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статусы заказов'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='tagandproduct',
            options={'verbose_name': 'Тег и продукт', 'verbose_name_plural': 'Теги и продукты'},
        ),
        migrations.AlterModelOptions(
            name='typeofpayment',
            options={'verbose_name': 'Типы оплаты', 'verbose_name_plural': 'Типы оплаты'},
        ),
        migrations.AddField(
            model_name='employee',
            name='employees_position',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_dismissal',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='commentary_for_order',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_img/'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tags_img/'),
        ),
    ]
