# Generated by Django 4.1.7 on 2023-05-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_customer_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='image',
        ),
        migrations.AddField(
            model_name='tag',
            name='board_image',
            field=models.ImageField(blank=True, null=True, upload_to='tags_img/board'),
        ),
        migrations.AddField(
            model_name='tag',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='tags_img/icon'),
        ),
    ]
