# Generated by Django 4.2.1 on 2023-05-12 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_tag_image_tag_board_image_tag_icon_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderposition',
            old_name='product',
            new_name='price_list_position',
        ),
    ]
