# Generated by Django 4.2.1 on 2023-05-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_product_orderposition_price_list_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='title_for_topic',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Наименование для тега'),
        ),
    ]
