# Generated by Django 4.2.1 on 2023-05-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_tag_title_for_topic_alter_tag_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='products.tag', verbose_name='Теги'),
        ),
        migrations.AlterModelTable(
            name='tagandproduct',
            table='products_product_tag',
        ),
    ]
