# Generated by Django 4.2.1 on 2023-05-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_tagandproduct_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='products.tag', verbose_name='Теги'),
        ),
    ]
