# Generated by Django 4.2.1 on 2023-05-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterModelTable(
            name='tagandproduct',
            table=None,
        ),
    ]
